### ISSUE TITLE
metrics - Replace input box of tenants with dropdown, or at least add a "send/submit" button next to it

### ISSUE THREAD

**Issue by abonas** [hawkular/hawkular-ui#17]
Dropdown box for tenants list is the most user friendly option.
If not, at least a send/submit button.
An input box like now is a bit misleading, especially since the input box is for the tenant name, and what appears under it are the metrics, not possible matching tenant names.
And as such, in addition, I suggest to also add a title to the metrics that appear under the tenant's input box

**Comment by jotak** [comment]
The layout already changed a bit with this PR #13 
Now the tenant is configured via another page (configuration), along with authentication
See the screenshots: http://imgur.com/a/H568Z

It's still not a dropdown list because the `/tenants` endpoint is admin-protected.

**Comment by abonas** [comment]
If not dropdown, at least worth to add a send/submit button next to it.

**Comment by jotak** [comment]
It's now ok there's a form with submit button
